// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Cambrian.Persistence.Migrations;

[DbContext(typeof(CambrianDbContext))]
[Migration("20260713002141_AddTrackAiDisclosureFoundation")]
public sealed partial class AddTrackAiDisclosureFoundation
{
}
